version: '2'
services:

    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        expose:
            - 3306
        networks:
            - vertical
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - ./wp-content:/var/www/html/wp-content
        expose:
            - 80
        networks:
            - vertical
            - nginx-proxy
        environment:
            VIRTUAL_HOST: vertical.localhost
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        expose:
            - 80
        networks:
            - vertical
            - nginx-proxy
        environment:
            VIRTUAL_HOST: phpmyadmin.vertical.localhost
            PMA_USERNAME: wordpress
            PMA_PASSWORD: wordpress
            PMA_HOSTS: db
            PHP_MAX_INPUT_VARS: 10000

volumes:
    db_data:

networks:
    vertical:
    nginx-proxy:
        external:
            name: proxy_default
